name: "Setup Environment"
description: "Sets up Node.js, pnpm with caching, and installs dependencies"

inputs:
    ref:
        description: "The Git ref to checkout. If not provided, no checkout is performed."
        required: false
        default: ""
    fetch-depth:
        description: "Number of commits to fetch. 0 indicates all history."
        required: false
        default: "1"

runs:
    using: "composite"
    steps:
        - name: Checkout repository
          if: inputs.ref != ''
          uses: actions/checkout@v4
          with:
              ref: ${{ inputs.ref }}
              fetch-depth: ${{ inputs.fetch-depth }}

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version-file: ".nvmrc"

        - name: Setup pnpm
          uses: pnpm/action-setup@v4
          with:
              run_install: false

        - name: Get pnpm store directory
          id: pnpm-cache
          shell: bash
          run: |
              echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

        - name: Setup pnpm cache
          uses: actions/cache@v4
          with:
              path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ runner.os }}-pnpm-store-

        - name: Install dependencies
          shell: bash
          run: pnpm install
