packages:
  - .
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
patchedDependencies:
  '@semantic-release/git@10.0.1': patches/@semantic-release__git@10.0.1.patch
  semantic-release@24.2.3: patches/semantic-release@24.2.3.patch
