blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/spencerbeggs/zsh-nvm-pnpm-auto-switch/discussions
    about: Please ask and answer questions here.
