blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/spencerbeggs/zsh-nvm-pnpm-auto-switch/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/spencerbeggs/zsh-nvm-pnpm-auto-switch#readme
    about: Check the README for detailed usage instructions.
