name: Pull Request Validation

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]

# Add permissions for checks
permissions:
    contents: read
    pull-requests: write
    checks: write

jobs:
    commitlint:
        name: Conventional Commits
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - uses: ./.github/actions/setup

            - name: Fetch base branch for comparison
              run: |
                  git fetch origin ${{ github.base_ref }}

            - name: Validate Conventional Commits
              run: |
                  echo "Validating commit messages between origin/${{ github.base_ref }} and HEAD"
                  pnpm commitlint --from=origin/${{ github.base_ref }} --to=HEAD --verbose

    lint:
        name: Code Quality
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: ./.github/actions/setup

            - name: Run ESLint
              run: pnpm lint

    test:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: ./.github/actions/setup

            - name: Install Zsh for tests
              run: sudo apt-get update && sudo apt-get install -y zsh

            - name: Set CI environment variable
              run: echo "CI=true" >> $GITHUB_ENV

            - name: Run tests
              run: pnpm test

    verify-all:
        name: Summary
        needs: [commitlint, lint, test]
        runs-on: ubuntu-latest
        if: always()
        steps:
            - name: Check job statuses
              run: |
                  if [[ "${{ needs.commitlint.result }}" == "success" && "${{ needs.lint.result }}" == "success" && "${{ needs.test.result }}" == "success" ]]; then
                    echo "All validation checks passed!"
                    exit 0
                  else
                    echo "One or more validation checks failed. Please review the details in each job."
                    exit 1
                  fi
