name: "Syntax Check"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * 0'  # Run at 1:30 AM UTC every Sunday

# Limit concurrent runs of this workflow to avoid resource contention
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  syntax-check:
    name: Shell Scripts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Zsh
      run: sudo apt-get update && sudo apt-get install -y zsh

    - name: Check Zsh script syntax
      run: |
        echo "Checking Zsh script syntax..."
        exitcode=0
        for file in $(find . -name "*.zsh" -o -name "*.plugin.zsh"); do
          echo "Checking $file"
          zsh -n "$file" || exitcode=$?
        done
        exit $exitcode

    - name: Check Bash script syntax
      run: |
        echo "Checking Bash script syntax..."
        exitcode=0
        for file in $(find . -name "*.sh"); do
          echo "Checking $file"
          bash -n "$file" || exitcode=$?
        done
        exit $exitcode
